GET http://localhost:3000/

###
GET http://localhost:3000/producto

###
POST http://localhost:3000/producto
Content-Type: application/json

{
    "nombre": "mesa",
    "precio": 40,
    "cantidad": 1,
    "imagen": "no hay"
}

###
GET http://localhost:3000/producto/2

###
PATCH http://localhost:3000/producto/3
Content-Type: application/json

{
    "nombre": "celular",
    "precio": 1300,
    "cantidad": 5,
    "imagen": "no hay"
}

###
DELETE http://localhost:3000/producto/2